import oji from "../../assets/images/fauzihaqmuslim.jpg";

export const Doctor = [
  {
    _id: 1,
    first_name: "fauzi",
    last_name: "haq muslim",
    work_address: "Klinik selalu sehat Jl. jalan sore No.10 RT/RW 012/013, ciganjul Jakarta",
    region: "bekasi",
    experience_year: 7,
    star: 5,
    price: 200000,
    avatar_url: oji,
    patient: {
      _id: 1,
      image: oji,
      name: "oji",
      birthDate: "1979",
      gender: "Male",
      email: "oji@mail.com",
      address:
        "Jln. Kenangan, No. 20 RT/RW 25/02, Kel. Suka Suka, Kec. Tidak Suka, Bekasi, Jawa Barat, Indonesia",
      complaints:
        "Sudah lama saya pacaran dengan pacar saya, sudah lebih dari 10 tahun. Tapi entah kenapa saya tidak merasa bahagia setiap kali kami bertemu saya tidak pernah di akuinya sebagai pacar, tidak pernah foto bareng saya dan selalu menjaga jarak minimal 5 meter dengan saya. Saya menjadi stress dan depresi, saya tidak dahu lagi harus bagaimana.",
      allergy: "Sakatonik ABC",
      diagnose: "Stress mikirin pacar",
      date: "10/12/2020",
      Time: "14.00",
      statusPaid: true,
    },
  },
  {
    _id: 2,
    first_name: "Naufal",
    last_name:"al-fachri",
    work_address: "Klinik selalu sehat Jl. jalan sore No.10 RT/RW 012/013, ciganjul Jakarta",
    region: "jakarta",
    experience_year: 2,
    star: 5,
    price: 200000,
    avatar_url: oji,
   patient: {
      _id: 2,
      image: oji,
      name: "Naufal",
      birthDate: "1979",
      gender: "Male",
      email: "naufal@mail.com",
      address:
        "Jln. Kenangan, No. 20 RT/RW 25/02, Kel. Suka Suka, Kec. Tidak Suka, Bekasi, Jawa Barat, Indonesia",
      complaints:
        "Sudah lama saya pacaran dengan pacar saya, sudah lebih dari 10 tahun. Tapi entah kenapa saya tidak merasa bahagia setiap kali kami bertemu saya tidak pernah di akuinya sebagai pacar, tidak pernah foto bareng saya dan selalu menjaga jarak minimal 5 meter dengan saya. Saya menjadi stress dan depresi, saya tidak dahu lagi harus bagaimana.",
      allergy: "Sakatonik ABC",
      diagnose: "Stress mikirin pacar",
      date: "10/12/2020",
      Time: "14.00",
      statusPaid: true,
    },
  },
  {
    _id: 3,
    first_name: "Raka",
    last_name: "khairil",
    work_address: "Klinik selalu sehat Jl. jalan sore No.10 RT/RW 012/013, ciganjul Jakarta",
    region: "depok",
    experience_year: 5,
    star: 5,
    price: 4000000,
    avatar_url: oji,
    patient: {
      _id: 3,
      image: oji,
      name: "Raka",
      birthDate: "1979",
      gender: "Male",
      email: "raka@mail.com",
      address:
        "Jln. Kenangan, No. 20 RT/RW 25/02, Kel. Suka Suka, Kec. Tidak Suka, Bekasi, Jawa Barat, Indonesia",
      complaints:
        "Sudah lama saya pacaran dengan pacar saya, sudah lebih dari 10 tahun. Tapi entah kenapa saya tidak merasa bahagia setiap kali kami bertemu saya tidak pernah di akuinya sebagai pacar, tidak pernah foto bareng saya dan selalu menjaga jarak minimal 5 meter dengan saya. Saya menjadi stress dan depresi, saya tidak dahu lagi harus bagaimana.",
      allergy: "Sakatonik ABC",
      diagnose: "Stress mikirin pacar",
      date: "10/12/2020",
      Time: "14.00",
      statusPaid: true,
    },
  },
];
